from datetime import datetime, timezone
from enum import Enum
from sqlalchemy import Boolean, DateTime, Enum as SAEnum, ForeignKey, Integer, JSON, String, Text
from sqlalchemy.orm import Mapped, mapped_column
from app.core.database import Base

def now(): return datetime.now(timezone.utc)
class Severity(str, Enum): CRITICAL="CRITICAL"; HIGH="HIGH"; MEDIUM="MEDIUM"; LOW="LOW"; INFO="INFO"
class FindingStatus(str, Enum): OPEN="OPEN"; IN_PROGRESS="IN_PROGRESS"; RESOLVED="RESOLVED"; IGNORED="IGNORED"
class ScanStatus(str, Enum): QUEUED="QUEUED"; RUNNING="RUNNING"; COMPLETED="COMPLETED"; FAILED="FAILED"
class RemediationStatus(str, Enum): PENDING_APPROVAL="PENDING_APPROVAL"; APPROVED="APPROVED"; IN_PROGRESS="IN_PROGRESS"; COMPLETED="COMPLETED"; REJECTED="REJECTED"
class User(Base):
    __tablename__="users"; id: Mapped[int]=mapped_column(primary_key=True); email: Mapped[str]=mapped_column(String(255),unique=True,index=True); password_hash: Mapped[str]=mapped_column(String(255)); full_name: Mapped[str]=mapped_column(String(255)); role: Mapped[str]=mapped_column(String(50),default="analyst"); created_at: Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now)
class AWSAccount(Base):
    __tablename__="aws_accounts"; id: Mapped[int]=mapped_column(primary_key=True); user_id: Mapped[int]=mapped_column(ForeignKey("users.id")); account_name: Mapped[str]=mapped_column(String(255)); aws_account_id: Mapped[str]=mapped_column(String(12)); region: Mapped[str]=mapped_column(String(50)); status: Mapped[str]=mapped_column(String(50),default="active"); created_at: Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now); last_scan_at: Mapped[datetime|None]=mapped_column(DateTime(timezone=True))
class Resource(Base):
    __tablename__="resources"; id: Mapped[int]=mapped_column(primary_key=True); aws_account_id: Mapped[int]=mapped_column(ForeignKey("aws_accounts.id")); resource_type: Mapped[str]=mapped_column(String(100)); resource_id: Mapped[str]=mapped_column(String(255)); name: Mapped[str]=mapped_column(String(255)); region: Mapped[str]=mapped_column(String(50)); status: Mapped[str]=mapped_column(String(50),default="active"); metadata_json: Mapped[dict]=mapped_column("metadata",JSON,default=dict); created_at: Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now); updated_at: Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now,onupdate=now)
class SecurityRule(Base):
    __tablename__="security_rules"; id: Mapped[int]=mapped_column(primary_key=True); rule_id: Mapped[str]=mapped_column(String(50),unique=True); name: Mapped[str]=mapped_column(String(255)); description: Mapped[str]=mapped_column(Text); service: Mapped[str]=mapped_column(String(50)); severity: Mapped[Severity]=mapped_column(SAEnum(Severity)); enabled: Mapped[bool]=mapped_column(Boolean,default=True); recommendation: Mapped[str]=mapped_column(Text); created_at: Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now)
class Finding(Base):
    __tablename__="findings"; id: Mapped[int]=mapped_column(primary_key=True); aws_account_id: Mapped[int]=mapped_column(ForeignKey("aws_accounts.id")); rule_id: Mapped[int|None]=mapped_column(ForeignKey("security_rules.id")); title: Mapped[str]=mapped_column(String(255)); description: Mapped[str]=mapped_column(Text); evidence: Mapped[dict]=mapped_column(JSON,default=dict); severity: Mapped[Severity]=mapped_column(SAEnum(Severity)); status: Mapped[FindingStatus]=mapped_column(SAEnum(FindingStatus),default=FindingStatus.OPEN); service: Mapped[str]=mapped_column(String(50)); resource_id: Mapped[str]=mapped_column(String(255)); resource_type: Mapped[str]=mapped_column(String(100)); region: Mapped[str]=mapped_column(String(50)); recommendation: Mapped[str]=mapped_column(Text); detected_at: Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now); resolved_at: Mapped[datetime|None]=mapped_column(DateTime(timezone=True))
class Scan(Base):
    __tablename__="scans"; id: Mapped[int]=mapped_column(primary_key=True); aws_account_id: Mapped[int]=mapped_column(ForeignKey("aws_accounts.id")); status: Mapped[ScanStatus]=mapped_column(SAEnum(ScanStatus),default=ScanStatus.QUEUED); started_at: Mapped[datetime|None]=mapped_column(DateTime(timezone=True)); completed_at: Mapped[datetime|None]=mapped_column(DateTime(timezone=True)); resources_scanned: Mapped[int]=mapped_column(Integer,default=0); findings_created: Mapped[int]=mapped_column(Integer,default=0); security_score: Mapped[int|None]=mapped_column(Integer)
class Remediation(Base):
    __tablename__="remediations"; id: Mapped[int]=mapped_column(primary_key=True); finding_id: Mapped[int]=mapped_column(ForeignKey("findings.id")); status: Mapped[RemediationStatus]=mapped_column(SAEnum(RemediationStatus),default=RemediationStatus.PENDING_APPROVAL); requested_by: Mapped[int]=mapped_column(ForeignKey("users.id")); approved_by: Mapped[int|None]=mapped_column(ForeignKey("users.id")); created_at: Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now); completed_at: Mapped[datetime|None]=mapped_column(DateTime(timezone=True)); notes: Mapped[str|None]=mapped_column(Text)
class Report(Base):
    __tablename__="reports"; id: Mapped[int]=mapped_column(primary_key=True); aws_account_id: Mapped[int]=mapped_column(ForeignKey("aws_accounts.id")); title: Mapped[str]=mapped_column(String(255)); type: Mapped[str]=mapped_column(String(50),default="posture"); security_score: Mapped[int]=mapped_column(Integer); generated_at: Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now); file_path: Mapped[str|None]=mapped_column(String(500))
