apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cloudguard
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
    - hosts: [cloudguard.example.com]
      secretName: cloudguard-tls
